name: NetBSD Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: '10.0' }
          - { version: '9.4'  }

    concurrency:
      group: ${{github.ref}}-${{github.workflow}}-${{matrix.version}}-${{matrix.deps}}
      cancel-in-progress: true

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Startup VM
      uses: cross-platform-actions/action@v0.25.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: runner-to-vm
        shutdown_vm: false
        run: true
    - name: Info
      uses: cross-platform-actions/action@v0.25.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sysctl -n hw.ncpu
          uname -a
          echo $PKG_PATH
          cat /usr/pkg/etc/pkgin/repositories.conf
    - name: Install dependencies
      uses: cross-platform-actions/action@v0.25.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          sudo pkgin -y update
          sudo pkgin -y full-upgrade
          sudo pkgin -y install subversion-base p5-subversion py311-subversion ruby32-subversion
          sudo pkgin -y install subversion
    - name: Test
      uses: cross-platform-actions/action@v0.25.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: false
        run: |
          echo "Success"
    - name: Shutdown VM
      uses: cross-platform-actions/action@v0.25.0
      with:
        architecture: x86_64
        memory: 4G
        operating_system: netbsd
        version: ${{matrix.version}}
        shell: bash
        sync_files: false
        shutdown_vm: true
        run: true
